config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'public_recipes#index'
  resources :public_recipes, only:[:index]
  resources :shopping_list, only: [:index]
  resources :users
  resources :recipes, only: %i[index show new create destroy update] do
    resources :recipe_foods, only: %i[new create destroy update edit] 
  end
  resources :foods, only: %i[index show new create destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: { message: "Name can't be null" }
  validates :description, presence: { message: "Description can't be null" }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all.where(user: current_user)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    flash[:notice] = "#{recipe.name} was successfully deleted"
    recipe.destroy
    redirect_to recipes_path
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(permitted_parameters_recipe)
    @recipe.user = current_user
    if @recipe.valid?
      @recipe.save
      redirect_to recipes_path, notice: "Recipe: #{@recipe.name} created successfully"
      return
    end
    redirect_to new_recipe_path
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.recipe_foods.includes(%i[recipe food])
    @recipes = Recipe.all
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    @recipe.save
    @recipe.public
    render 'recipes/status_changed'
  end

  private

  def permitted_parameters_recipe
    params.require(:recipe).permit(:name, :description, :cookingTime,
                                   :preparationTime, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/add_ingredient.html.erb
<%= turbo_frame_tag "addIngredient" do%>
  <%= form_for(@ingredient, url:add_ingredient_recipe_path, method: :post)  do |form| %>
    <%= form.label :food_id, "Food", class:"form-label" %>
    <%= form.select :food_id, current_user.foods.map{|food| [food.name, food.id]}, required: true %>
    <%= form.label :quantity, "Quantity", class:"form-label " %>
    <%= form.number_field :quantity, required: true %>
    <%= form.submit "Add ingredient", class: "btn btn-outline-primary" %>
    <%= link_to "Close", recipe_path(@recipe), class:"btn btn-outline-secondary"  %>
  <% end %>
<% end %>

app/views/recipes/add_ingredient.turbo_stream.erb
  <%= turbo_stream.prepend "ingredients" do%>
    <%= render partial: "shared/ingredient", locals: {ingredient: @ingredient}%>
  <% end %>

app/views/recipes/index.html.erb
<h1 class="mt-2 text-center">Recipes</h1>
<%= link_to 'Add new recipe', new_recipe_path, 
  class: 'btn btn-primary btn-sm float-end mb-4'
%>
<div class="container mt-5" style="clear:both;">
  <%@recipes.each do |recipe|%>
    <div class="float-none card mt-3">
      <div class="card-body">
        <h3 class="card-title"><%=recipe.name%></h3>
        <p class="card-text"><%= recipe.description%></p>
          <%= link_to "See Details", recipe,
            class: 'btn btn-primary' %>
          <%= link_to "Remove", recipe, data: {turbo_method: :delete, turbo_confirm: "Are you sure"},
          class: 'btn btn-danger' %>
      </div>
    </div>
  <%end%>
<div>

app/views/recipes/modify_ingredient.html.erb
<%= turbo_frame_tag dom_id(@ingredient) do%>
  <%= form_for(@ingredient, 
    url: update_ingredient_recipe_path(id:@ingredient.id)) do |form|%>
    <div class="d-flex mt-1 align-items-center">
    <%= form.label :quantity, class:"label-control me-1 ms-1" %>
    <%= form.number_field :quantity, class:"form-control me-1"%>
    </div>
    <%= form.submit "Update", class:"btn btn-warning m-1"%>
    <%= link_to "Back", recipe_path(@ingredient.recipe.id), class:"btn btn-primary"%>
  <% end %>
<% end%>

app/views/recipes/new.html.erb
<h1 class='text-centered mt-3 mb-3'>
  New recipe
</h1>
<div class="container">
<%= form_with(model: @recipe, 
  data: { turbo: false }) do |f| %>
  <div class="mb-3">
    <%= f.label :name,  class: "form-label" %>
    <%= f.text_field :name, autofocus: true, class:"form-control"%><br />
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, autofocus: true, class:"form-control" %><br />
    <%= f.label :preparationTime, 'Preparation time (minutes)', class: "form-label"%>
    <%= f.number_field :preparationTime, in: 1.0..4320.0, step: 0.5, 
    autofocus: true, title: "Enter time in minutes", class:"form-control"%>
    <%= f.label :cookingTime, 'Cooking time (minutes)', class: "form-label" %>
    <%= f.number_field :cookingTime, in: 1.0..4320.0, step: 0.5, 
      autofocus: true, title: "Enter time in minutes", class:"form-control"%>
  </div>
  <div class="mb-3 d-flex align-items-baseline">
    <%= f.label :public, "Make this recipe public", class: "form-label" %>
    <%= f.check_box :public, autofocus: true, class:"form-check", class: "ms-2"%>
  </div>
  
  <%= f.submit "Create recipe", class:"btn btn-primary" %>
<%end%>
</div>

app/views/recipes/show.html.erb
<h1 class='text-center mb-3 mt-2'>
  <%=@recipe.name%>
</h1>
<div class='d-flex info-recipe justify-content-between '>
  <div class=''>
    <p class='mb-3 fs-5 fw-bold'>
      Preparation time: 
      <span class="fw-normal"><%=@recipe.preparationTime%> minutes</span> 
    </p>
    <p class='mb-3 fs-5 fw-bold'>
      Cooking time: 
      <span class="fw-normal"><%=@recipe.cookingTime%> minutes</span> 
    </p>
    <p class='mb-3 fs-5'>Steps go here ...</p>
  </div>
  <div class=''>
    <% if can? :manage, @recipe %>
      <%= render partial:"shared/publicRecipe"%>
    <% end %>
  </div>
</div>
<div class='d-flex mb-4'>
  <% if can? :manage, @recipe %>
    <%=button_to 'Generate shopping list', shopping_list_index_path,
      method: :get,
    class: 'btn btn-primary btn-sm me-2'%>
    <%= turbo_frame_tag "addIngredient" do%>
      <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), class: "btn btn-primary btn-sm"%>
    <% end %>
  <%end%>
</div>
<hr>
<div>
  <div>
    <div class="d-flex border-bottom border-info mb-3">
        <p style="flex:1" class="fw-bold">Food</p>
        <p style="flex:1" class="fw-bold">Quantity</p>
        <p style="flex:1" class="fw-bold"">Value</p>
        <% if can? :manage, @recipe %>
          <p style="flex:1" class="fw-bold">Actions</p>
        <%end%>
    </div>
    <%= turbo_stream_from "ingredients"%>
      <%= turbo_frame_tag "ingredients" do%>
          <% @ingredients.each do |ingredient| %>
            <%= render partial: "shared/ingredient", locals: {ingredient: ingredient}%>
          <% end %>
      <% end %>
  </div>
</div>

app/views/recipes/status_changed.html.erb
<%= render partial:"shared/publicRecipe"%>