config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'public_recipes#index'
  resources :public_recipes, only:[:index]
  resources :shopping_list, only: [:index]
  resources :users
  resources :recipes, only: %i[index show new create destroy update] do
    resources :recipe_foods, only: %i[new create destroy update edit] 
  end
  resources :foods, only: %i[index show new create destroy]
end

app/views/shared/_flash.html.erb
<% if flash.any?%>
  <% flash.each do |name, msg| -%>
    <%if name=='alert'%>
      <div class='alert alert-danger flash' 
        data-controller="removals" data-action="animationend->removals#remove">
        <%=msg%>
      </div>
    <%else%>
      <div class='alert alert-info flash'
      data-controller="removals" data-action="animationend->removals#remove">
       <%=msg%>
      </div>
    <% end %>
  <% end %>
<%end%>

app/views/shared/_ingredient.html.erb
<div>
  <turbo-frame id= <%= dom_id(ingredient)%> class="d-flex" >
      <div style="flex:1"><%= ingredient.food.name%></div>
      <div style="flex:1"> <%=ingredient.quantity%> <%= ingredient.food.measurementUnit%></div>
      <div style="flex:1"><%= number_to_currency ingredient.food.price * ingredient.quantity%></div>
      <% if can? :manage, ingredient.recipe %>
        <div style="flex:1">
          <%= link_to "Modify", 
            edit_recipe_recipe_food_path(ingredient.recipe, ingredient),
            class: 'btn btn-warning btn-sm m-1'
          %>
          <%= link_to "Delete", 
            recipe_recipe_food_path(ingredient.recipe, ingredient),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure"},
            class: 'btn btn-danger btn-sm m-1'
          %>
        </div>
      <% end %>
  </turbo-frame>
</div>

app/views/shared/_navBar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Recipe App</a>
    <% if user_signed_in?%>
      <p class="fs-6 mb-0">Welcome: <%=current_user.name%></p>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "Foods", foods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Shopping List", shopping_list_index_path, class: "nav-link" %>
        </li>
        <li>
         <% if user_signed_in?%>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:'nav-link' %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class:'nav-link' %>
        <%end%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_publicRecipe.html.erb
<turbo-frame id="toggle-public" class="switch-container">
  <form action=<%=recipe_path(id:@recipe.id)%> data-remote="true" method="patch">
    <label>Public </label>
    <label class="switch">
      <input type="submit"  class=<%=@recipe.public ? 'public' : '' %>
            />
      <span class="slider"/>
    </label>
  </form>
</turbo-frame>