config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'public_recipes#index'
  resources :public_recipes, only:[:index]
  resources :shopping_list, only: [:index]
  resources :users
  resources :recipes, only: %i[index show new create destroy update] do
    resources :recipe_foods, only: %i[new create destroy update edit] 
  end
  resources :foods, only: %i[index show new create destroy]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :recipe_foods

  validates :name, presence: { message: "Name can't be null" }
  validates :measurementUnit, presence: { message: "Measurement unit can't be null" }
  validates :price, presence: { message: "Price can't be null" }
  validates :price, numericality: { only_float: true, greater_than: 0, message: 'Price must be greater than 0' }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
    @foods = current_user.foods.all
  end

  def new
    @food = Food.new
    @current_user = current_user
  end

  def create
    @food = current_user.foods.new(food_params)
    if food_params[:price].to_f.positive?
      if @food.save
        flash[:success] = "#{@food.name} was successfully created"
        redirect_to foods_url
      else
        flash[:alert] = "#{@food.name} was not created"
        redirect_to new_food_url
      end
    else
      flash[:alert] = 'Price must be greater than 0'
      redirect_to new_food_url
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @check_food = RecipeFood.where(food: @food)
    if @check_food.count.positive?
      flash[:alert] = "#{@food.name} belongs to some recipes"
    else
      flash[:notice] = "#{@food.name} was successfully deleted"
      @food.destroy
    end
    redirect_to foods_url
  end

  def food_params
    params.require(:food).permit(:name, :measurementUnit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<h2 class="text-center">Create a new food</h2>
<%= form_with scope: :food, url: foods_path, method: :post  do |form| %>
  <div class="mb-3">
    <%= form.label :name,class:"form-label" %>
    <%= form.text_field :name, required: true, autofocus: true, class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :name,"Measurement unit",class:"form-label" %>
    <%= form.text_field :measurementUnit, required: true, class:"form-control" %>
  </div>
  <div class="mb-3">
   <%= form.label :price,class:"form-label" %>
    <%= form.text_field :price, required: true, type: "number", 
    step: "0.01", value: 0.1, id: "price_input",
    class:"form-control" %>
  </div>
<br>
<%= form.submit 'Save food', :class => 'btn btn-primary' %>
<%= link_to 'Back', url_for(:back), :class => 'btn btn-secondary float-right' %>
<% end %>


<% if flash[:notice] %>
    <div class="alert-pos" id="notice"><%= flash[:notice] %></div>
<% end %>

app/views/foods/index.html.erb
<h1 class="mt-2 text-center">Foods</h1>
<%= link_to 'Add new food', new_food_path, :class => 'btn btn-sm float-end btn-primary mt-1 mb-4' %>
<div class="margin-table">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Food</th>
        <th>Measurement unit</th>
        <th>Unit price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
        <td><%= food.name%></td>
        <td><%= food.measurementUnit%></td>
        <td><%= number_to_currency food.price%></td>
        <td>
          <%= link_to "Delete", food, 
            data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},
            class:"btn btn-danger"%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div> 

app/views/foods/new.html.erb
<%= render 'foods/form' %>